language: php

php:
  - 5.6

before_install:
  - cd selenium-tests/

install:
  - composer install --no-interaction
  - ./vendor/bin/steward.php install --no-interaction

before_script:
  - java -jar ./vendor/bin/selenium-server-standalone-2.45.0.jar -role hub &
  - sleep 2
  - phantomjs --webdriver-selenium-grid-hub=http://127.0.0.1:4444 --webdriver= &
  - sleep 2

script:
  - ./vendor/bin/steward.php run-tests production phantomjs
