language: php

php:
  - 5.6
  - 7

addons:
  firefox: "47.0.1" # Firefox 47.0.1 is the latest Firefox which does not require Geckodriver (but it is compatible only with Selenium 2.53.1)

env:
  - BROWSER=phantomjs
  - BROWSER=firefox

matrix:
  include:
    - php: 7
      env: BROWSER=phantomjs USE_STEWARD_MASTER=1 # run tests also against Steward master branch

before_install:
  - cd selenium-tests/
  - export SELENIUM_SERVER_VERSION="2.53.1" # Selenium server 2.53.1 is the only version comaptible with Firefox 47.0.1

install:
  - composer install --no-interaction # Install Steward and its dependencies
  - if [ -n "$USE_STEWARD_MASTER" ]; then composer require lmc/steward:dev-master --update-with-dependencies; fi
  - SELENIUM_PATH=$(./vendor/bin/steward install $SELENIUM_SERVER_VERSION --no-interaction) # Download the Selenium standalone server jar file
  - echo "Selenium server path:" $SELENIUM_PATH

before_script:
  - java -jar $SELENIUM_PATH -role hub -log selenium-server.log &
  - until $(echo | nc localhost 4444); do sleep 1; echo Waiting for selenium-server to start...; done;

  # Start two PhantomJS instances
  - if [ "$BROWSER" = "phantomjs" ]; then phantomjs --webdriver-selenium-grid-hub=http://127.0.0.1:4444 --webdriver=8910 & fi
  - if [ "$BROWSER" = "phantomjs" ]; then phantomjs --webdriver-selenium-grid-hub=http://127.0.0.1:4444 --webdriver=8911 & fi

  # Start first Firefox instance
  - if [ "$BROWSER" = "firefox" ]; then Xvfb :99 -nolisten tcp -ac -screen 0 1280x1024x24 & fi
  - if [ "$BROWSER" = "firefox" ]; then export DISPLAY=:99.0; fi
  - if [ "$BROWSER" = "firefox" ]; then java -jar $SELENIUM_PATH -role node -port 8910 -maxSession 1 & fi

  # Start second Firefox instance
  - if [ "$BROWSER" = "firefox" ]; then Xvfb :98 -nolisten tcp -ac -screen 0 1280x1024x24 & fi
  - if [ "$BROWSER" = "firefox" ]; then export DISPLAY=:98.0; fi
  - if [ "$BROWSER" = "firefox" ]; then java -jar $SELENIUM_PATH -role node -port 8911 -maxSession 1 & fi

  - sleep 3 # wait until browsers starts

script:
  - ./vendor/bin/steward run production -vvv $BROWSER # Run the tests in $BROWSER and specify `production` as an environment name

after_script:
  - cat selenium-server.log
